name: cash_flow
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.1+1
  get: 4.6.5
  get_storage: ^2.0.3
  intl: ^0.17.0
  path: ^1.8.1
  sqflite: ^2.0.3

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Decker
      fonts:
        - asset: fonts/DeckerB.ttf
          weight: 700
        - asset: fonts/Decker.ttf
  assets:
    - assets/background_circles.svg
    - assets/dots_rectangle.svg
    - assets/striped_oval.svg
    - assets/sample_logo.svg
